
name: To run helloworld

on:
  push:
    branches: [ "main", "vamshi" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, Vamshi!

      - name: Run a multi-line script
        run: echo This is second stage
